name: Release

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
      - rc
jobs:
  publish:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Build Package
        run: yarn build
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
